name: "Auto approve Dependabot minor updates"

on:
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-approve:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.TOKEN }}"
      - uses: hmarr/auto-approve-action@v3
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        with:
          github-token: "${{ secrets.TOKEN }}"
